### ISSUE TITLE
ParseRSAPublicKeyFromPEM returns wrong error ErrNotRSAPrivateKey (copy+paste issue?)

### ISSUE THREAD

**Issue by jonathaningram** [SermoDigital/jose#19]
See https://github.com/SermoDigital/jose/blob/master/crypto/rsa_utils.go#L65

It is:

```go
return nil, ErrNotRSAPrivateKey
```

Should it be another new error type `ErrNotRSAPublicKey`?

**Comment by EricLagergren** [comment]
Yes, I do think you are correct. I will go fix that. Thank you!
