### ISSUE TITLE
jwt.io debugger

### ISSUE THREAD

**Issue by deviantmk** [SermoDigital/jose#2]
Hello,

I was just trying to debug a jwt token on http://jwt.io and i cant get it to validate there (Invalid Signature).
i tried both HS256 and RS256 but to no vail, shouldn't it work since it uses the same specification?

**Comment by EricLagergren** [comment]
Works on our end.

Here's what we used:

JWT:

**Comment by EricLagergren** [comment]
![works](https://cloud.githubusercontent.com/assets/5894247/11967778/a53d5ce4-a8ba-11e5-9753-fbf4df8be449.png)

**Comment by deviantmk** [comment]
are you able to confirm this for HS256 too?

**Comment by EricLagergren** [comment]
`go get -u ...`

hmac was summing more than it needed to.

and then try this: 
![works2](https://cloud.githubusercontent.com/assets/5894247/11987443/4757a244-a994-11e5-8462-fba0b47fea02.png)

**Comment by deviantmk** [comment]
again, thanks for looking into it and the prompt fix

**Comment by EricLagergren** [comment]
you're welcome!
