### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by Noah-Huppert** [SermoDigital/jose#31]
In the docs there is a typo: if has 2 "f"s in [jwt/eq.go#23](https://github.com/SermoDigital/jose/blob/master/jwt/eq.go#L23)  

A super tiny error that really doesn't matter that much. Just didn't know where else to report it. Feel free to close if something this small isn't worth fixing.

**Comment by ericlagergren** [comment]
thanks for catching this!

**Comment by ericlagergren** [comment]
Looking back at this, I likely wrote iff on purpose (meaning if and only if like @ anshnd mentioned).

Thanks for letting us know!
