### ISSUE TITLE
Wrong comparison in Audience validation

### ISSUE THREAD

**Issue by andrefreitas** [SermoDigital/jose#5]
I am testing my JWT Factory (GenerateJWT) that receives parameters from a HTTP request.

When comparing parsed claims with the expected claims, the validation will fail because the expected claims is a slice and the parsed one is a string: (I placed a breakpoint at jwt/jwt.go)

```go
(godebug) l

    	if jti, ok := v.Expected.JWTID(); ok &&
    		j.Claims().Get("jti") != jti {
    		return ErrInvalidJTIClaim
    	}
--> 	_ = "breakpoint"
    	if aud, ok := v.Expected.Audience(); ok &&
    		!eq(j.Claims().Get("aud"), aud) {
    		return ErrInvalidAUDClaim
    	}

(godebug) p v.Expected.Audience()
[]string{"report"}, true
(godebug) p j.Claims().Get("aud")
"report"
```

JWT package have no tests. I can send some PR to fix these bugs and have tests, if they are welcome.

**Comment by andrefreitas** [comment]
Update: when comparing, you should use the same method to retrieve Audience, Subject and etc:
If you use Audience() instead of Get("aud") you should get the right types:
```go
(godebug) p j.Claims().Get("aud")
"report"
(godebug) p j.Claims().Audience()
[]string{"report"}, true
```

**Comment by EricLagergren** [comment]
I think it'd be a better API if setting the audience only ever took `...string` (since the RFC allows one or more string values). It'd also internal comparisons easier since it'd just require comparing two slices.

I'll get back to this + your PR in a bit after a meeting.

**Comment by EricLagergren** [comment]
Just noticed I forgot to close this.

Thanks again for the PR!.
